version: '3'
services:
    mongodb:
      container_name: mongodb-exchange
      image: mongo:latest
      ports:
          - 27017:27017

    redis:
      container_name: redis
      image: redis:4.0.6
      ports:
        - 6379:6379
      links:
        - mongodb

    app:
      build: .
      command: yarn dev
      ports:
          - 4000:4000
      environment: 
          MONGO_URL: mongodb
          PORT: 4000
      volumes:
          - .:/src
          - nodemodules:/node_modules
      links:
          - mongodb
      depends_on: 
          - mongodb
          - redis
volumes:
  nodemodules: {}