version: '3'
services:
    mongodb:
      container_name: mongodb
      image: mongo:4
      ports:
          - 27017:27017
    app:
      build: .
      command: yarn dev
      ports:
          - 4000:4000
      environment: 
          PORT: 4000
      volumes:
          - .:/src
          - nodemodules:/node_modules
      links:
          - mongodb
      depends_on: 
          - mongodb
volumes:
  nodemodules: {}

